Repository abhiChakra/mapnimity, pull requests merged in 2020-12, with the labels that each got.

#1 Rename folders and move into src
  src/api/.gitignore
  src/api/package.json
  src/api/src/index.js
  src/app/.gitignore
  src/app/README.md
  src/app/package.json
  src/app/public/index.html
  src/app/public/manifest.json
  src/app/public/robots.txt
  src/app/src/App.js
  src/app/src/App.test.js
  src/app/src/index.js
  src/app/src/reportWebVitals.js
  src/app/src/setupTests.js
Labels: enhancement, good first issue

#2 Create basic endpoint for api
  src/api/.gitignore
  src/api/src/index.js
  src/api/src/package.json
Labels: enhancement

#3 convert location strings to a midpoint latlng
  src/api/.gitignore
  src/api/src/dotenv.sh
  src/api/src/index.js
  src/api/src/package.json
  src/api/src/utils/calculateMidpoint.js
Labels: enhancement

#6 refactor frontend code to use latest react
  src/app/src/App.test.js
  src/app/src/MainHome.js
  src/app/src/setupTests.js
Labels: enhancement

#9 dope work on getting restaurants and increasing radius
  src/api/src/index.js
Labels: enhancement

#8 Get map and fix css styling and functionality
  src/app/package.json
  src/app/public/index.html
  src/app/src/App.js
  src/app/src/MainHome.js
  src/app/src/MapContain.js
  src/app/src/MenuAppBar.js
  src/app/src/PlacesInput.js
  src/app/src/css/MainHome.css
  src/app/src/index.css
Labels: enhancement

#10 Get current location and restaurants on map and fix backend bug
  src/api/src/index.js
  src/app/src/MainHome.js
  src/app/src/MapContain.js
Labels: bug, enhancement

#12 fix key issue and add price/rating
  src/app/src/MainHome.js
  src/app/src/MapContain.js
Labels: enhancement

#13 add architecture/design diagrams
  documentation/architecture/architecture-workflow.png
  documentation/design/ui-mockup.png
Labels: documentation, enhancement

#16 Saucey Mausi
  src/api/src/index.js
  src/app/package.json
  src/app/src/MainHome.js
  src/app/src/MapContain.js
Labels: bug, enhancement

#18 add postman collection and fix bug
  postman/mapnimity-api.postman_collection.json
  src/app/public/index.html
  src/app/src/MainHome.js
  src/app/src/MapContain.js
Labels: bug, enhancement

#19 change placeholder and label
  src/app/src/PlacesInput.js
Labels: enhancement

#20 cleanup and disable button on click
  src/app/public/img/logo.png
  src/app/src/MainHome.js
  src/app/src/MenuAppBar.js
  src/app/src/css/MainHome.css
Labels: enhancement

#22 tests
  src/api/src/index.js
  src/api/src/package.json
  src/api/src/tests/endpoints.test.js
Labels: enhancement

#21 Update README.md
  README.md
  src/app/README.md
Labels: documentation

#23 Update README.md
  README.md
Labels: documentation
